server:
  port: 4300
  
logging:
  level:
    web: DEBUG

jwt:
  rsaKey: "poner clave privada"
  expiration: 3600000

spring:
  cloud:
    gateway:
      routes:
      - id: service
        uri: http://httpbin.org
        predicates:
        - Path=/get
        filters:
        - BodyToJWS